use students111;
select * from ddetails_3;
select sum(physics) from ddetails_3;
select Department from ddetails_3 where Department like '%A';
select name from ddetails_3 where name like '%A';
alter table ddetails_3 drop totalmarks;
alter table ddetails_3 add total int;
update ddetails_3 set total="255" where id=1;
update ddetails_3 set total="251" where id=2;
update ddetails_3 set total="243" where id=3;
update ddetails_3 set total="212" where id=4;
update ddetails_3 set total="207" where id=5;
update ddetails_3 set total="264" where id=6;
update ddetails_3 set total="147" where id=7;
update ddetails_3 set total="215" where id=8;
update ddetails_3 set total="264" where id=9;
update ddetails_3 set total="147" where id=10;
alter table ddetails_3 add age int;
update ddetails_3 set age="24" where id=1;
update ddetails_3 set age="22" where id=2;
update ddetails_3 set age="23" where id=3;
update ddetails_3 set age="25" where id=4;
update ddetails_3 set age="24" where id=5;
update ddetails_3 set age="21" where id=6;
update ddetails_3 set age="25" where id=7;
update ddetails_3 set age="23" where id=8;
update ddetails_3 set age="24" where id=9;
update ddetails_3 set age="25" where id=10;
alter table ddetails_3 add constraint test check(age>=21);
create view stud_details as select id,name from ddetails_3;
select * from stud_details;
delete from ddetails_3 where age=22;
commit;
select * from ddetails_3;
rollback;
